<?php

namespace app\common\model;

use think\Model;

class Base extends Model
{
    protected $autoWriteTimestamp = 'timestamp';

    public static function className() {
        return get_called_class();
    }

    protected static function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
